;;; package  --- Summary
;;; Commentary:


;;; Code:
(load "~/.emacs.d/my-loadpackages.el")



;; Generic Settings
(setq make-backup-files nil) ;; disable backup files
(scroll-bar-mode -1) ;; Disable Scroll Bar
(tool-bar-mode -1)
(define-coding-system-alias 'UTF-8 'utf-8) ;; Add utf encoding support
(setq-default tab-width 2 indent-tabs-mode nil)
(setq inhibit-startup-message t) ;; hide splash screen
(setq gdb-many-windows t)
(global-set-key (kbd "s-f") 'toggle-frame-fullscreen) ;; Fullscreen shortcut
(server-start)


(require 'evil)
(evil-mode 1)
(setq evil-emacs-state-cursor '("#A6E22E" box))
(setq evil-normal-state-cursor '("#F92672" box))
(setq evil-visual-state-cursor '("#66D9EF" box))
(setq evil-insert-state-cursor '("#A6E22E" bar))
(setq evil-replace-state-cursor '("#A6E22E" bar))
(setq evil-operator-state-cursor '("#A6E22E" hollow))

(require 'company)
(add-hook 'after-init-hook 'global-company-mode)

;; Syntastic
(require 'flycheck)
(global-flycheck-mode t)

(require 'monokai-theme)
;; ------------- AutoGenerated Stuffs -----------------
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("0eebf69ceadbbcdd747713f2f3f839fe0d4a45bd0d4d9f46145e40878fc9b098" default)))
 '(haskell-mode-hook (quote (turn-on-haskell-indentation))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(provide '.emacs)
;;; .emacs ends here
